version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pipefy_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:15-alpine
    container_name: pipefy_postgres_test
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres_db_test

    ports:
      - "5433:5432"

volumes:
  postgres_data: